name: Lint

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Run linter and formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
      - run: pnpm i
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linter
        run: pnpm lint
      - name: Run formatter
        run: pnpm format
